### ISSUE TITLE
Support for schema shorthand notation

### ISSUE THREAD

**Issue by jimkyndemeyer** [graphql/codemirror-graphql#14]
Hey.

Thanks for this project. It's been hugely helpful in bringing GraphQL to the IntelliJ family.

Are there any plans to add support for the schema shorthand notation?

If not, and you're open to it, I'll see if I can find the time to do a PR. I'm assuming you'll prefer a separate mode like what was just added for variables?

**Comment by leebyron** [comment]
Yes, the plan is to add the schema language notation as well, likely part of the same mode just for simplicity.

**Comment by stubailo** [comment]
I'd definitely be interested in this as well, since we're exploring methods to write a GraphQL server that rely heavily on the schema language!

**Comment by leebyron** [comment]
Fixed by #20

**Comment by jimkyndemeyer** [comment]
Awesome. Thanks.
