### ISSUE TITLE
Where is graphql-language-service-interface@0.4.0 source code?

### ISSUE THREAD

**Issue by bakso** [graphql/codemirror-graphql#172]
Not on branch or tag

**Comment by wincent** [comment]
Thanks for the question, @bakso.

Everything is on the `master` branch in [the graphql-language-service repo](https://github.com/graphql/graphql-language-service/). Specifically, this the so-called "monorepo" approach, and you can find the individual packages in [the "packages" directory](https://github.com/graphql/graphql-language-service/tree/master/packages). We don't tag the individual subpackages yet, but we may do that in the future (our other projects use a Travis-based publishing mechanism, that pushes to NPM for us when we push a new tag to GitHub, but we have to sort out some kinks in the monorepo flow before we can do something similar for the graphql-language-service packages).

For now, in the absence of tags, you have to look at the `package.json` history, which will lead you [here](https://github.com/graphql/graphql-language-service/commit/55c2a914768b911716d7f04bc1b58757cb1e120c) in the case of graphql-language-service-interface@0.4.0.
