### ISSUE TITLE
When will you publish 0.6.4?

### ISSUE THREAD

**Issue by bakso** [graphql/codemirror-graphql#175]
Do you have a road map for the developer to keep up with your step?

**Comment by wincent** [comment]
No we don't. At the moment codemirror-graphql is basically "feature complete" so there's not much call for a roadmap. I'll cut a release this week, however.

**Comment by asiandrummer** [comment]
@bakso I'd love to chat with you if you're planning to use/contribute to the code! As @wincent mentioned this repo just wraps around the language service code (`graphql-language-service`) so there isn't much to do at this point, but I can definitely come up with something similar to the roadmap/wanted features for the language service.

**Comment by asiandrummer** [comment]
@wincent btw, I've merged the greenkeeper PRs and fixed the travis build so that the new version is ready to be released. It's kinda weird that `graphql-js` isn't being updated via greenkeeper - we should keep an eye out for that

**Comment by wincent** [comment]
Yeah, there is some voodoo in Greenkeeper that leads it to not make PRs for some packages. It's a mystery to me what heuristics it's using for that.

**Comment by wincent** [comment]
[v0.6.4 is now out](https://github.com/graphql/codemirror-graphql/releases/tag/v0.6.4).
