### ISSUE TITLE
The autocomplete doesn't show any description

### ISSUE THREAD

**Issue by imolorhe** [graphql/codemirror-graphql#195]
Hello,

So I have a project using codemirror and this package for working with graphql queries. Everything seems to work fine, but looking at the demo GIF on this repo, and in other projects, there is a description of the items in the autocomplete at the base of the autocomplete. I've not been able to get mine to show that description, and I am stuck at this point. Please any ideas on what is missing? https://github.com/imolorhe/altair/blob/staging/src/app/query-editor/query-editor.component.ts#L162

**Comment by asiandrummer** [comment]
Hey @imolorhe - sorry it took a while to get to you. Did you resolve this? The link shows me 404 at the moment.

**Comment by imolorhe** [comment]
@asiandrummer This is the current link: https://github.com/imolorhe/altair/blob/staging/src/app/components/query-editor/query-editor.component.ts#L134

I've not yet resolved it.

**Comment by asiandrummer** [comment]
@imolorhe I couldn't find where you're rendering the autocomplete results, but I'm throwing a random guess that you may be using an incorrect key name for accessing autocomplete result items. Below is the type:
```js
type AutocompleteResultItem = {
  text: string,
  type: GraphQLType,
  description?: string,
  isDeprecated: boolean,
  deprecationReason: string,
};
```

**Comment by imolorhe** [comment]
Do I need to specially render it? I just use it as any code mirror add-on. I didn't eclogite l explicitly render the autocomplete.

**Comment by asiandrummer** [comment]
You don't if you're using the stock `codemirror/show-hint` addon and just wanted to render the autocomplete result texts. As shown in [`show-hint` section in the addons page](http://codemirror.net/doc/manual.html#addons), `codemirror` won't understand the `description` key that we're passing from the autocomplete suggestion provider.

GraphiQL uses [a custom UI renderer](https://github.com/graphql/graphiql/blob/master/src/utility/onHasCompletion.js) to solve this.

**Comment by imolorhe** [comment]
Oh okay, makes sense now. Thanks.

**Comment by imolorhe** [comment]
I guess that bit is missed in the docs for this add on then.

**Comment by asiandrummer** [comment]
:D let me know if you have other questions! Closing this for now.
