### ISSUE TITLE
Problem with IDEOGRAPHIC SPACE (\u3000)

### ISSUE THREAD

**Issue by gfx** [graphql/codemirror-graphql#236]
I have problems with GraphiQL if a query includes IDEOGRAPHIC SPACE (`\u3000`).

I'm not sure it is a problem in codeirror-graphql or CodeMirror, but here is a reproducable test case which never completes (maybe with infinite loop?):

```patch
diff --git a/src/__tests__/mode-test.js b/src/__tests__/mode-test.js
index 77cc2b4..194b6d0 100644
--- a/src/__tests__/mode-test.js
+++ b/src/__tests__/mode-test.js
@@ -127,4 +127,19 @@ describe('graphql-mode', () => {
       },
     );
   });
+
+  it('deals with IDEOGRAPHIC SPACE', () => {
+    const queryStr = '\u3000'
+    const tokens = [];
+    const styles = [];
+
+    CodeMirror.runMode(queryStr, 'graphql', (token, style) => {
+      if (style && style !== 'ws') {
+        tokens.push(token);
+        styles.push(style);
+      }
+    });
+
+    expect(styles).to.deep.equal([]);
+  });
 });
```

**Comment by asiandrummer** [comment]
Hi @gfx - that's pretty weird to hear that it doesn't even complete running the mode. Our online parser complains if there isn't a rule matched, so it seems to be from CodeMirror's side, although I can't really be sure. Can we check CodeMirror's mode runner to see if there is any logic against special chars like this?

**Comment by asiandrummer** [comment]
I'm going to close this due to inactivity. As far as I know there's no support towards chars like this, and I'm doubtful that we need to start supporting them. If you have a clear use case that must use special chars like ideographic space, please reopen and we can work together!

**Comment by cpojer** [comment]
@asiandrummer this definitely still seems like an issue. I just tried to use graphiql and accidentally switched my keyboard to Japanese, ended up typing an invalid character and now that graphiql instance is completely busted to the point that I don't know how to reset the query :(
