### ISSUE TITLE
Should peer dependency on graphql be OK with graphql 0.11.x?

### ISSUE THREAD

**Issue by glasser** [graphql/codemirror-graphql#239]
The peer dependencies listed here don't include graphql 0.11.x, which has been out for two months. Is there an incompatibility or does it just need to be updated?

**Comment by Yogu** [comment]
The greater problem is that this one depends on `graphql-language-service-interface@^0.1.13` which [installs graphql@0.10 as dependency, not peerDependency](https://github.com/graphql/graphql-language-service/blob/v0.1.13/packages/interface/package.json).

**Comment by asiandrummer** [comment]
They just all need to be updated. I need to go do a massive clean-up soon - sorry for the false positive errors/warnings.

**Comment by danez** [comment]
I created a PR a while ago that should fix it. #235

**Comment by asiandrummer** [comment]
Merged - thanks and sorry @danez for the PR/delay. Will cut a release shortly!
