### ISSUE TITLE
How to bring graphql schema from server to client?

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [graphql/codemirror-graphql#255]
Hello everyone,
         I am using graphql java implementation and codemirror in client side to test graphql apis. Now i need to show type suggestion in client side. After many search i ended up here [https://github.com/graphql/codemirror-graphql](url), how to pass graphql schema to codemirror. How to bring schema from java server side to client side.
        I heard we can using query interpolation to build schema in client side, if this possible plz explain how to do this.

**Comment by IvanGoncharov** [comment]
@KarthikNedunchezhiyan You need to call two function from `graphql-js`:
* `getIntrospectionQuery` to generate query that you need to send to the server:
https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js#L18
* `buildClientSchema` that you need to call with query results:
https://github.com/graphql/graphql-js/blob/master/src/utilities/buildClientSchema.js#L80
