### ISSUE TITLE
Add fragment suggestion

### ISSUE THREAD

**Issue by ykad4** [graphql/codemirror-graphql#7]
Hi, 
Thank for this awesome project and graphQL in general, what a revolution.
I use intelliJ Idea with [JS GraphQL IntelliJ Plugin](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin), I noticed it didn't suggest fragment when I type "...", this would be a nice feature if it's not too much to ask.
Thank you again.

**Comment by asiandrummer** [comment]
Thanks for kind words :D I think it's a good idea to provide fragment suggestions (the list of defined fragments and `or` word for inline fragments), in addition to the Type Conditions (`... on {Type}`) we already provide suggestions for. I think we have a couple of issues (#4 for example) to resolve before this, but I'd love to support this feature. @leebyron thoughts?

**Comment by leebyron** [comment]
This will be released shortly!

**Comment by ykad4** [comment]
Great work, Thanks.
